### ISSUE TITLE
Backslashes (\) in "posix-win32-cmake/dpp/Resource.rc" incompatible with MinGW 'windres'

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpc-examples#2]
The double backslashes (\\) in path definitions (IDB_BTN_DWN, etc.) are incompatible with MinGW's implementation of the resource compiler (`windres`)

So the lines like
`IDB_BTN_DWN             BITMAP                  "Res\\BTN_DWN.bmp"`
should read
`IDB_BTN_DWN             BITMAP                  "Res/BTN_DWN.bmp"`
to work with MinGW.

Is Microsoft's resource compiler compatible with this syntax?

**Comment by quantum-leaps** [comment]
Done.
--MMS

**Comment by stefanschober** [comment]
Thanks :)
